language: php

php:
  - 7.4

services:
  - mysql
  -
env:
  global:
    - secure: your-encrypted-variable-1=
    - secure: your-encrypted-variable-2=

install:
  - mysql -e 'CREATE DATABASE test_lsp;'
  - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json

before_script:
  - travis_retry composer update --no-interaction --no-suggest --prefer-source

script:
  - vendor/bin/phpunit -v
