<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ApiController
 *
 * @internal
 * @coversNothing
 */
class ApiControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invokeReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('page.api'));

        $response->assertOk();
        $response->assertViewIs('api');
        $response->assertViewHas('endpoints');
        $response->assertViewHas('xData');

        // TODO: perform additional assertions
    }

    // test cases...
}
