<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\EventListController
 *
 * @internal
 * @coversNothing
 */
class EventListControllerTest extends TestCase
{
    /**
     * @test
     */
    public function indexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('events'));

        $response->assertOk();
        $response->assertViewIs('events.index');
        $response->assertViewHas('eventsPerMonth');
        $response->assertViewHas('events');
        $response->assertViewHas('monthlyLinks');
        $response->assertViewHas('canonical');
        $response->assertViewHas('display');

        // TODO: perform additional assertions
    }

    // test cases...
}
