<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\HomeController
 *
 * @internal
 * @coversNothing
 */
class HomeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function invokeReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('home'));

        $response->assertOk();
        $response->assertViewIs('home');
        $response->assertViewHas('thisWeek');
        $response->assertViewHas('nextWeek');

        // TODO: perform additional assertions
    }

    // test cases...
}
