<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\IcalController
 *
 * @internal
 * @coversNothing
 */
class IcalControllerTest extends TestCase
{
    /**
     * @test
     */
    public function eventReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('event.ics', ['uuid' => $uuid]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function feedReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('ics'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
