<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\VenueListController
 *
 * @internal
 * @coversNothing
 */
class VenueListControllerTest extends TestCase
{
    /**
     * @test
     */
    public function indexReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('venues'));

        $response->assertOk();
        $response->assertViewIs('venues.index');
        $response->assertViewHas('venuesAlpha');
        $response->assertViewHas('top');

        // TODO: perform additional assertions
    }

    // test cases...
}
