<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\VenueController
 *
 * @internal
 * @coversNothing
 */
class VenueControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function showReturnsAnOkResponse()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $venue = factory(\App\Venue::class)->create();

        $response = $this->get(route('venue', ['slug' => $venue->slug]));

        $response->assertOk();
        $response->assertViewIs('venues.show');
        $response->assertViewHas('venue');
        $response->assertViewHas('upcomingEvents');
        $response->assertViewHas('pastEvents');

        // TODO: perform additional assertions
    }

    // test cases...
}
